export const ValidatorLengths = {
  'FIRST_NAME_MIN': 3,
  'FIRST_NAME_MAX': 32,
  'LAST_NAME_MIN': 3,
  'LAST_NAME_MAX': 32,
  'EMAIL_MAX': 50,
  'MOBILE_MIN': 10,
  'CONTENT_TITLE_MIN': 3,
  'CONTENT_TITLE_MAX': 64,
  'CONTENT_DESC_MIN': 3,
  'CONTENT_DESC_MAX': 150,
  'PASSWORD_MIN': 8,
  'PASSWORD_MAX': 32,
  'COURSE_NAME_MIN': 3,
  'COURSE_NAME_MAX': 30
};
